### ISSUE TITLE
Build component for searching for Orgs

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_frontend_prototype#10]
Build out a Typeahead component that allows a user to call OpenSearch to find Orgs that match the user's entry as they type.

Refer to the work already done in the DMPTool repo's `react-client`. This will need to be updated though to call OpenSearch.

We will need a broad one that searches across all orgs and one that is more refined to search by type (e.g. funder or non-funder)

**Comment by mariapraetzellis** [comment]
This requires that the OpenSearch API is connected, which is tracked here: https://github.com/CDLUC3/dmsp_aws_prototype/issues/84

**Comment by bofstein** [comment]
Built something for pilot project to transfer from
Requires the BE table to be able to build from, needs the endpoints
Dependent on this ticket: https://github.com/CDLUC3/dmsp_aws_prototype/issues/85

**Comment by bofstein** [comment]
Also needs https://github.com/CDLUC3/dmsp_aws_prototype/issues/84 to get the newest org data

**Comment by bofstein** [comment]
![image](https://github.com/user-attachments/assets/b0825e0f-505e-4eaa-8979-237352966179)

This version looks good to me if we fix the spacing around the first parentheses, rather than using a separate checkbox for Other, as that might be covered when typing.

If it's too long we can change it later to just "Organization not listed"

**Comment by jupiter007** [comment]
Ok thanks @bofstein. I will remove the TypeAhead component that does not include "Other" then.

**Comment by bofstein** [comment]
Now I will say I'm not sure if there's anywhere else on the site we might use a typeahead without a pinned Other option if it's a component we'd re-use.

**Comment by jupiter007** [comment]
Ok, well maybe I'll keep the other one just in case, for now, and just change the "Other" language to the one you proposed above.
