### ISSUE TITLE
Tabs component for template templates

### ISSUE THREAD

**Issue by fraserclark** [CDLUC3/dmsp_frontend_prototype#108]
We talked a bit about on the call yesterday if these "tabs" on the "Edit question" and "Edit Section" within the template builder are "real tabs" or just navigational elements to pages

template/{id}/q/{quid}/options
template/{id}/q/{quid}/logic

![Image](https://github.com/user-attachments/assets/a5674a61-298e-4f45-b334-828b0842ea2e)

![Image](https://github.com/user-attachments/assets/dcd3cd81-cca4-4efa-976b-a506faec0633)

I think I lean towards just making them "real tabs", there isn't much in the tabs either and they are conceptually editing the same thing. 

There 2 big advantages of it being "pages" rather than tabs 

- Easier bookmarking
- Back button in the browser will work

We can "work around" these 2 big advantages to some extent 

Let me know your thoughts

**Comment by fraserclark** [comment]
As a part of the style guide, I have styled these in the PR - it is real tabs as agreed above, so completely dynamic etc no page changes etc

https://github.com/CDLUC3/dmsp_frontend_prototype/pull/120

Basic style guide version could be used for anything
![Image](https://github.com/user-attachments/assets/6ed5248e-9dde-4ca0-930a-d8460b745569)

A more realistic example of it being used 
![Image](https://github.com/user-attachments/assets/ef7bf4d6-17fa-4e57-b79a-208ec9d87fe7)

**Comment by jupiter007** [comment]
Hi @fraserclark , I just wanted to confirm that this ticket has been completed.
