### ISSUE TITLE
Wireframe amends, September 5th

### ISSUE THREAD

**Issue by cazinc** [CDLUC3/dmsp_frontend_prototype#109]
Hello, 

We have several amends to various parts of the Creating a Plan ready for you. Please visit https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=1511-764&t=ZTnkDLeyqpMiy6kc-1 and note the following:

1. Overall changes include breadcrumbs at the top and some copy changes to try and make things more clear. 
1. **Mark as complete/Publish amends**: Instead of "Save as draft" we now have "Mark as complete". This brings up a popup that lets the user download, as we anticipate this being the common task in mind, and nudges the user towards publishing (final "why you should publish" text TBD). Publishing works as before, but it now feels more separate, in line with discussions. 
2. **Request feedback/Share**: We've re-termed "share" as "access settings" in attempt to make it more clear what this is for, but also added a "Request feedback" button to reflect actual user goals. Clicking the Request feedback button also shows where a new "Feedback from your university librarian" would be integrated (not yet built). 
3. **Plan members**: we've implemented changes here to firstly intro new "members" terminology, where _members_ are other users who have a role on the project and/or plan, distinct from the concept of research collaborators/co-authors. Secondly, these changes show how users could manage different lists of members for the overall project versus each plan. Click **Adjust for this plan** next to **Members for this plan**  and you'll see that all the overall project members are available by default, but users can remove or add people, and also change their role for just the current plan. 
4. **Multiple funders**: click **Adjust for this plan** next to **Funder for this plan** and you'll see that, much like above, users can select the funder for a specific plan. It works much like project/plan members: there's a list of overall funder(s) for a project, and users can designate which funder is applicable to a specific plan. 

We also have some small amends to questions at https://www.figma.com/design/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=1511-462&t=ZTnkDLeyqpMiy6kc-1.
1. **Comments**: this are a bit more prominent, and the red dot indicates "new comments". 
2. **Request feedback**: As above, we've added a request feedback button here for easier access to this. 
3. **Breadcrumbs and wayfinding nav at left**: We briefly discussed these on Tuesday, both are meant to help users better understand where they at to support a more "linear" flow if they wish. 
4. **Sample text**: We've moved the button for sample text up, but haven't yet put the actual sample text here. We're looking for a way to respond to tester feedback and make this more obvious/accessible while preventing long or multiple sample answers from pushing the question itself even further down. Thoughts? 
5. **"External" best practice guidance**: As discussed we've got a new model for DMP Tool best practice guidance in place here, for discussion. On the one hand it moves the content "out of the way" but on the other it probably would end up in it being less used. The idea is that this would still be based on tags, btw. We said on Tuesday we're not in love with this, it's more an experiment. Let us know what you think.

**Comment by briri** [comment]
@bofstein is it ok to close this one?

**Comment by bofstein** [comment]
@fraserclark @cazinc 

I left a couple comments I'd like to see addressed before closing it.  Overall the updates look great, the only part I'm unsure about is the way we added the Mark as Complete. amends. 

We also got some new feedback we may want to consider but that can be a a new ticket not added to this one.

**Comment by fraserclark** [comment]
Thanks @bofstein - we will try to get this addressed before Thursday's call and can chat about it

**Comment by bofstein** [comment]
Thank you!  And to be clear if you have a good reason for it "addressing" it could be explaining it to me if you feel this is the right path. Open to that or changes.

**Comment by bofstein** [comment]
I think we're good here!
