### ISSUE TITLE
Build contents of Your Profile page

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#124]
Building this page on the front end: https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=771-1054&t=LIKQ4JuadoMKIEAS-8&scaling=scale-down-width&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1772&show-proto-sidebar=1&hotspot-hints=0&hide-ui=1

Will want to use errors and layout from registration, wait until that is built:
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=736-1822&t=LIKQ4JuadoMKIEAS-8&scaling=scale-down-width&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1772&show-proto-sidebar=1&hotspot-hints=0&hide-ui=1

After making an update, the info changes and you stay on the page

**Email and authentication**

Will need [#table](https://github.com/CDLUC3/dmsp_backend_prototype/issues/105) done to be able to integrate and test emails

This is only building the text boxes of aliases - will make separate tickets for the email flow of confirming an alias.  When an email is entered though, have a notification that the email has been sent: "Check your email to confirm the new address and have it added to your aliases."

Notifications not linked yet but will be a separate page

**Comment by bofstein** [comment]
Acceptance criteria:
- Page exists on dev, can be navigated to
- Page has left sidebar with tabs (even if other pages don't exist yet)
- Users can see their current information, and can update it
- Updating information uses same logic is signing up with new information (e.g. institution list)
- Users can change their language, which immediately takes affect and turns the page into that language 
- Users see a list of all of their confirmed email addresses
- Users can see which email is primary and which are secondary
- Users can remove emails from their account after a double confirmation
- Users can change on of their secondary emails into their primary email
- Users can enter an email to add as an alias/secondary email.  This will eventually send an email to them to verify that but that is in a separate ticket
- Page follows current style guide, and can be updated if that is updated (e.g. for colors and font)

**Comment by jupiter007** [comment]
I believe I completed the User Profile page. We don't yet have localization in place, so contrary to above Acceptance criteria, when a user selects a language, the text will always be in English.

I am putting my changes into PR review.
