### ISSUE TITLE
Build email confirmation flow for adding alias emails - FE

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#125]
Make a generic page that doesn't need to be logged in with a message:

"Thanks for confirming your alias email.  Click below to log in and access your plans.  Remember you still need to use your primary email to log in."

Under it have a button to login. 

We can use this to build a generic page design to use for messages like this (and 404, down for maintenance, etc).  Can be white box with text on main grey page with header.

**Comment by bofstein** [comment]
Will wait for https://github.com/CDLUC3/dmsp_frontend_prototype/issues/126

**Comment by jupiter007** [comment]
We'll be using a generic page for this. Here is a link to the wireframe for a generic page:
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=2293-1385&node-type=frame&t=eX1fgwI5TfzbQsgl-0&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=2341%3A317&show-proto-sidebar=1

**Comment by jupiter007** [comment]
This ticket is just to build a basic page. However, its functionality will depend on these backend tickets:

- Email alias db table (https://github.com/CDLUC3/dmsp_backend_prototype/issues/105)
- Email service (https://github.com/CDLUC3/dmsp_backend_prototype/issues/106)

**Comment by jupiter007** [comment]
@bofstein if the verification fails, what message do we want to display to the user?

**Comment by jupiter007** [comment]
The assumption for this flow, for now, will be that users will be redirected to a NextJS page and that page will call an API endpoint in the backend to verify the email. If the verification succeeds, the user will be redirected to a "success" confirmed-email page with a "Log in" button.  So, the verification will not happen after the user logs in.
