### ISSUE TITLE
Research and discuss localization options for app

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#160]
Juliet to start researcher/reading about options, Becky will schedule meeting with team and Marisa to review options

**Comment by jupiter007** [comment]
The team met with Marisa and static files are ok, but we want to use something like "translation.io" to allow translations to happen and then automate the static file updates. We need to research which libraries and software is available to work with `next-intl`.

Separately, we have to discuss how we want to manage site-wide messaging in a database.

**Comment by jupiter007** [comment]
Looks like `next-intl` recommends using [Crowdin](https://next-intl-docs.vercel.app/docs/workflows/localization-management) for managing translations. Sent Crowdin a message to see if they provide free educational licenses.

**Comment by jupiter007** [comment]
**Simple Lingui/ translation.io test:**

1. Ran: 
```
npm install @translation/lingui
npm install --save-dev @lingui/cli @lingui/macro
npm install --save-dev @babel/core babel-plugin-macros
npm install @lingui/react
```
2. Added these scripts to app
```
{
  "scripts": {
    "sync": "lingui extract --overwrite && lingui compile",
    "sync_and_purge": "lingui extract --overwrite --clean && lingui compile"
  }
}
```
3. Created a `lingui.config.js` file with:
```
import { formatter } from "@lingui/format-json"

export default {
  // ... other Lingui configurations
  locales: [
    "en",
    "pt"
  ],
  sourceLocale: "en",
  catalogs: [
    {
      path: "messages/{locale}/messages",
      include: [
        "app", "components"
      ],
      exclude: ['node_modules', '.next']
    }
  ],
  service: {
    name: "TranslationIO",
    apiKey: "a6cb86674be34e1b93d655b155f29ff6"
  },
  format: 'po',
  messageId: 'message'
};
```
4. Followed instructions here to set up layout.tsx: https://translation.io/docs/guide-to-translate-your-lingui-applications

5. Updated `app/account/connections/page.tsx` to include:
```
import { Trans } from '@lingui/macro';
<h1><Trans>Connections</Trans></h1>
```
6. Ran `npx lingui extract`
7. Ran `npx lingui compile` to compile files into JavaScript modules
8. Logged into translation.io, and I could see the column where I could translate "Connections"
9. However, when I ran the app, I was getting the error "Unsupported Server Component type: undefined" when starting the app. I don't think NextJs is compatible with "translation.io" because it wants to do both client and server rendering.

**Comment by jupiter007** [comment]
Will try and follow these instructions from "lingui" as a next step: https://lingui.dev/tutorials/react-rsc

**Comment by jupiter007** [comment]
1. Set up a project called "dmptool" in Crowdin. 
2. Requested a free account as an open source project here: https://crowdin.com/page/open-source-project-setup-request
3. Did some more simple translations tests.
4. Requested a demo from Crowdin rep, Andriy Stets

**Comment by jupiter007** [comment]
So, it seems like **Crowdin** should work for us. I read that it works with NodeJS as well.

For the NextJS app, using **next-intl** seems to be the best option for us. It integrates well with NextJS apps, and it makes setting up routing with language codes easy. The only inconvenience is that we have to insert keys for translations into all of our components.

**Comment by jupiter007** [comment]
Links to some demos, provided by Crowdin:
Github integration: https://store.crowdin.com/github
In-Context: https://store.crowdin.com/in-context

**Comment by jupiter007** [comment]
Things to consider:
1. Make sure to sanitize any translations 
2. Make sure that variables can be used with translations, like "Hello {}"
3. Research ways to secure download of Crowdin translations

**Comment by bofstein** [comment]
@jupiter007 and @bofstein to review this for CrowdIn: https://docs.google.com/document/d/1wuEkNvXUVZU9Wy-a9eca1WcV9lfWE2EhGy9STZVgoas/edit?tab=t.0#heading=h.qrop50ips5jl

**Comment by bofstein** [comment]
Questions to look over:
- Number and types of roles in our free plan
- Limits of free plan (e.g. word count) - do we have enough for our needs

**Comment by jupiter007** [comment]
I contacted Crowdin support and they said we have unlimited roles and users, as well as unlimited words. According to Crowdin, the open-source license doesn't directly correspond with any of their plans.

However, Marisa shared this note from their site: 
#Note: As an Open Source project maintainer by submitting the form you agree to:
join Crowdin beta group and try Crowdin's latest features,
contribute your project translations to Crowdin Global TM and gain access to Crowdin Neural Machine Translator.
The requirements do not apply to paid customers.
(https://crowdin.com/pricing)

@bofstein and @marisastrong what are your thoughts? Can we move forward with Crowdin?

**Comment by jupiter007** [comment]
Discussed this with @marisastrong and @bofstein in the #dmptool slack channel, and they are both ok with moving forward with using Crowdin as our localization management platform. So I will mark this ticket as "Done". Created a ticket to add Crowdin code to upload and download content (https://github.com/CDLUC3/dmsp_frontend_prototype/issues/196)
