### ISSUE TITLE
Evaluate Crowdin against template

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#184]
Juliet and Becky to fill out this (generally, not necessarily every question) for checking Crowdin: https://docs.google.com/document/d/1XUhue1h-MVybW1VddCjCkfCr47DPyfLRNWRZwrRH6EI/edit?tab=t.0

**Comment by jupiter007** [comment]
@bofstein - Can you let me know if there's anything else we need to do with this evaluation?
