### ISSUE TITLE
Contributor Role page

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_frontend_prototype#20]
Create a contributor role management page (template for any lookup tables)
- Only super admin can access
- Display existing as a list with fields (label, URL, active checkbox)
- Ability to delete, and add new
- Will incorporate Apollo Client GraphQL to make queries and mutations

The initial entries to use will be from the [Credit NISO taxonomy](https://jats4r.niso.org/credit-taxonomy/). 
```
[
  { "id": 1, "label": "Data Manager", "url": "https://credit.niso.org/contributor-roles/data-curation/" },
  { "id": 2, "label": "Principal Investigator", "url": "https://credit.niso.org/contributor-roles/investigation/" },
  { "id": 3, "label": "Project Administrator", "url": "https://credit.niso.org/contributor-roles/project-administration/" }
]
```

**Comment by jupiter007** [comment]
The Contributor Role page was created and the GraphQL calls to the development branch of the backend code was added and tested.
