### ISSUE TITLE
Create Figma wireframes for template picker

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmsp_frontend_prototype#31]
We discussed this during the Edinburgh meetings. Here is a summary from the notes: 

We discussed how it is potentially very complicated to help a Researcher pick the right template as there are lots of criteria to keep in mind. However, in the end we decided on a model where:
  - We give the Researcher a list of All Templates, but initially filtered by their research Organization and/or Funder (let them choose, combine, etc. with standard filter tools)
   - Also pre-filtered to show only Public Templates or templates shared with their organization as now
  - By using a standard Filter model, somewhat akin to what you might see on something like Amazon, we have certain advantages: users will be familiar with it for one, and also it will become easy to introduce other filters or sort tools (e.g. “Most Recent”, “Most Popular with your peers”, etc., “Your templates marked as Favorite”).

**Comment by jupiter007** [comment]
@cazinc. I'm sure @briri and Maria will have a better response, but it seemed like we needed the Research Organization search to further filter after selecting Funder, except maybe updating that search to include Field Stations?

**Comment by briri** [comment]
Hi @cazinc here are my thoughts on your questions:
1. Yes, I cannot think of a scenario where the researcher would filter on "has guidance" or "has samples". I like the concept of those checkmarks that appear on the cards though. I feel it could be used to highlight things like "funder approved" or "follows best practices", etc. I'm not sure how we can determine those from the data, but  I think some further discussion with Maria is needed for that. Regardless though, I can't really see any reason to filter on that type of information. 
2. Agreed. I am wondering if we just display the funder and research org as readonly info. Sort of a way to help illustrate why we're showing them the templates that appear initially when the page loads. For example in your Figma, it shows NIH as the funder so we're showing them the NIH templates.
3. Agreed. I think if it were read only (as mentioned above in #2). 

We currently only have around 45 funder templates, 2 field station templates and maybe a dozen research organization specific templates. I can see things growing there but not dramatically. 

I am wondering if we just show them their funder and research org with some text that explains why the initial template cards are displayed. The ones we would show on the initial load would be: Funder templates 1st, Research org specific template 2nd (if that is even applicable for their org).

Then we could have filters/controls to let them filter the cards that are displayed. Here are the scenarios: 
- **90% of scenarios:** I need to use the funder I specified's template (this person has no need to use filters)
- **Likely scenario:** My funder has a template, but I am going to do some of my research at a particular field station/lab and that field station/lab require me to fill out a plan based on their template
- **Somewhat likely scenario:**  I am an assistant for a researcher based at UC Berkeley. It's a joint project and the PI on the project is from Stanford. I was given the task to create a DMP for this project. Even though the funder has a template and I am from UC Berkeley (which also has a template), I was asked to use the Stanford template
- **Least likely scenario:** I said my funder was X but for some reason I want to use funder Y's template (in this case I wonder if we don't just have them go back and select the correct funder)

So I think the filters just need to allow the user to switch between:
- Selecting one of their Funder's templates 
- Tell us their field station/lab name and then select a template for that entity
- Tell us the name of a different research org and we show them the template (we can limit the org list here to only show ones that actually have a template)
- Use the default "best practice" template that. This one is used in scenarios where the funder and research org do not have a template, but the user should always be able to select it if they want.

**Comment by cazinc** [comment]
Hi @briri thanks for that feedback, super helpful. 

Based on this I've got a new version of the Template Picker wireframe at https://www.figma.com/proto/nkcgoqDZY49sKzZDtgxsiG/DMPTool-Phase-2?page-id=1901%3A124&node-id=1972-157&viewport=-836%2C1586%2C0.87&t=zUAZrthW50pW02GX-1&scaling=min-zoom&starting-point-node-id=1972%3A157

Changes:
1. User can turn on/off what is effectively a Funder filter. 
2. User can search by research org, field station, or anything else (a word in the template title/description for example) using the free text field. In conjunction with the tickbox on the Funder filter, they can have an and/or search. 
3. I've taken the Research Org field out completely.

So following your scenarios, here's how I think this latest version would work:

- 90%: the Funder filter is "on" by default - done!
- Likely 1: user can search by research org/field station in the free text field, and turn off the Funder filter
- Likely 2: if no funder associated with the project, then we could instead show Best Practice templates here (this is Option 2 in the prototype link above)
- Somewhat likely: user can turn the Funder filter OFF and then use free text to search for the Standard templates
- Least likely: I think the previous item would still apply here, but tend to agree that it'd be better for them to go back and pick a funder

See you shortly!

**Comment by briri** [comment]
@cazinc can you add a line to each of the template cards that indicates who the maintainer of the template is? We want to encourage admins to take ownership of maintaining a template

**Comment by cazinc** [comment]
Hi @briri both of these changes have been made now. 

- I've added "maintained by:" lines to various Templates on both versions. Per yesterday's chat, this does bring up some questions about how this would work: is it a contact point, would every template have a maintainer, what should a template that you created for a funder and that they are not maintaining show, etc. 
- Related to the above, I've bolded the "Last updated" info on a few of the templates to illustrate a simple way to perhaps accomplish a similar goal: highlighting which templates are being maintained (by implication of "recently updated"). 
- I've added "funder" to the description under the keyword field only on the version where Funder isn't specified, as per yesterday's chat I think this might cause confusion if the funder is already specified?

**Comment by mariapraetzellis** [comment]
We will only show the maintainer name not the org/email - we are trying to ensure they are credited for the contribution but they should not be responsible for fielding questions. 

Only display the last 3 names of the maintainers

**Comment by mariapraetzellis** [comment]
Thanks @cazinc these changes look good.
