### ISSUE TITLE
CDL to specify a specific browser spec to build to

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmsp_frontend_prototype#33]

**Comment by jupiter007** [comment]
I analyzed our website traffic using Matomo analytics over the past year to determine the most frequently used browsers. As expected, Chrome, Microsoft Edge, Safari, Firefox and Opera were at the top:
<img width="621" alt="image" src="https://github.com/CDLUC3/dmsp_frontend_prototype/assets/8452761/26310389-c09e-4aae-ab84-f106fcd904bc">

We need to make sure to support, at minimum, Chrome, Microsoft Edge, Safari and Firefox.

We will also want to consider, eventually, what devices we might want to focus on supporting. Even though Desktop use makes up the predominant number of users, smartphones are the second most common device in the last year:

<img width="630" alt="image" src="https://github.com/CDLUC3/dmsp_frontend_prototype/assets/8452761/9c305113-7dc0-4b2a-a917-9a443388c154">

Smartphone use only appears to be increasing, and it might make sense for us to support mobile device compatibility in more areas of our site.

**Comment by jupiter007** [comment]
@briri @mariapraetzellis let me know whether you are in agreement with supporting the following browsers for our new app: **Chrome**, **Microsoft Edge**, **Safari** and **Firefox**.

**Comment by briri** [comment]
Yes, I think we should support all of those browsers.

**Comment by mariapraetzellis** [comment]
Agreed, these browsers make sense.
