### ISSUE TITLE
Create style guide

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmsp_frontend_prototype#35]
The “living” styleguide will serve as a common place where any developer,
designer and even testers can look at the different components used in the app.
Developers can use the styleguide to develop functionality for their components,
without having to rely on certain front-end pages to be completed first.

- [x] Decide on a Structure

My immediate thoughts are that the structure in the beginning can just be a
single page, and we can just scroll to the components we want. A navbar could
help jump to a specific component.

As the list of components grow, we can potentially group related components
together on their own pages.

- [x] Create the page structure and add some initial components
- [x] For core library components, if we didn't add any custom styling to them, add a link to the core library component documentation so that developers can see how to use the component.
- [x] Documentation should include any /css variables/ that can change the look
      of the component.

**Comment by jupiter007** [comment]
Hi @andrewebdev. The TypeAhead.jsx component that I created for the dmptool is here, https://github.com/CDLUC3/dmptool/blob/v5/react-client/src/components/TypeAhead.jsx, and works with the backend that lives in the current dmptool repo. 

I think it's best to wait to add this component to the style guide until we are developing a page with a TypeAhead field and we have an available endpoint to call.

**Comment by briri** [comment]
I had started work on [a ticket that pulls in the institution information from ROR](https://github.com/CDLUC3/dmsp_aws_prototype/issues/84). We can point the typeahead field at that. We will need it anyway for the upcoming authentication work. We can reprioritize that for the next sprint.

**Comment by mariapraetzellis** [comment]
@jupiter007 will take a look and update the ticket with the current status.

**Comment by jupiter007** [comment]
@andrewebdev - I approved your PR.

**Comment by briri** [comment]
reopening so this stays on the board so we can review completed tasks at the end of the sprint
