### ISSUE TITLE
Question Type Spec

### ISSUE THREAD

**Issue by fraserclark** [CDLUC3/dmsp_frontend_prototype#48]
We have question types which will form the Template builder, however we need to scope these out a little, after we can wireframe them so we know what to build.

**Simple:**
Text field
Email field
URL field
Text area
Radio buttons
Check boxes
Select box
Multi-select boxes
Date field
Date range
Table (define #rows and cols and set heading text)

**Complex widgets**
Repository selector
Metadata standard selector
Output formats 
Licenses 
People (ORCID lookup)
Protocol selector
RRID selector
Genbank
Gene ontologies etc (look at CZI proposal) 
 

I think we need to define each something like the following structure for each.  We can then Wireframe these to help development of style guide etc

Type:  Text Field
Comment: Standard text field - no real special features
Requirement text: Yes
Guidance Text: Yes
Sample Answer : Yes
Default answer: No - this will be covered by sample text etc
Validation rules: Allow builder to as required, allow min and max length???
Allow for conditional logic? yes

Type: Radio buttons
Comment: Standard radio button - will allow for single selection of a radio button. The template builder must allow for key and label of each radio option must be editable 
Requirement text: Yes
Guidance Text: Yes
Sample Answer : n/a - as going to be yes/no
Default Answer: Yes - we want builder to be able to preselect a radio button 
Validation rules: required 
Allow for conditional logic? yes

Type: Repository selector
Comment: An autocomplete-like tool and repo selector API will be used, API is TBC. but it will return Repo Name to display to user and other meta data such as ID, Repo URL etc
Requirement text: Yes
Guidance Text: Yes
Sample Answer : n/a - as going to be yes/no
Default Answer: n/a
Validation rules: required 
Allow for conditional logic? no

**Comment by mariapraetzellis** [comment]
For now we will define these questions on a google doc and link here when done.

**Comment by mariapraetzellis** [comment]
We have started working on defining the specs [here](https://docs.google.com/document/d/1sRJ_K1u2eLU78vB_jqA25hJKbdOE1HPubTo626C02vA/edit).

We can get through the Simple question types this week. The Complex question types may take longer- will that hold you up @fraserclark?

**Comment by fraserclark** [comment]
@mariapraetzellis nope all good

**Comment by mariapraetzellis** [comment]
@fraserclark @cazinc I am considering closing this ticket and moving the "complex question" types to their own issues. I have finished defining the simple question types ([here](https://docs.google.com/document/d/1sRJ_K1u2eLU78vB_jqA25hJKbdOE1HPubTo626C02vA/edit), but the "complex" questions will take more time to define. Let's discuss at the next dev meeting.

**Comment by cazinc** [comment]
I think that's a good idea @mariapraetzellis - there's certainly enough material to warrant their own card. Thanks for letting us know.
