### ISSUE TITLE
Clarify state and visibility

### ISSUE THREAD

**Issue by cazinc** [CDLUC3/dmsp_frontend_prototype#49]
Hi, 

As with the maintainer question #47 we had a few questions about the various states for a template, since we're wireframing the tools for managing this right now. 

This is how we currently understand things:

**STATE**
- Deleted: A template that has been fully deleted (possibly in a temp "Trash" location). Probably not wanted/needed - Archived ("hidden but admin can still see it") better?
- Archived: Only visible to the Funder admin(s), not for use by researchers, no longer in use
- Draft: Only visible to the Funder admin(s), in process/not ready for use, will be published
- Published: Available for use in DMPTool

**VISIBILITY**
- Private: Only visible to logged in researchers (from any org)
- Public: Visible to anyone - I think we're maybe confusing this with a state that's applicable to Plans, not Templates? 

Assuming that's correct, we would see admin user flows for the lifetime of a template working something like this:
1. Create, save as draft until ready to publish
2. Publish when ready, mark as Private or Public
3. Archive when time to retire

Our questions come in mostly around whether there is any need for Private & Public visibility on a Template - is this really just for Plans? If so I think Visibility as a whole doesn't apply to Templates? In other words if a Template is Published, it's Visible, if it isn't, it's not? 

Are we missing anything?

**Comment by mariapraetzellis** [comment]
@cazinc There are times when an administrator might want a template visible to **any** user (including those from other orgs). So, we'll need two visibility states: 

- Visible to the organization 
- Visible to all DMP Tool users

**Comment by cazinc** [comment]
Thanks for that @mariapraetzellis. We're still a bit unclear on the use cases for this. 

The key one (we think) is that an Org acting as Funder or Org's FS may want to make their template visible to all, such as if researchers from a different org are involved in a project. Default visibility would be org only though. 

But use case is less clear when we're speaking of an **overlay** to an existing Funder template. Can you clarify when this would be viable to all? 

Any other cases?

**Comment by mariapraetzellis** [comment]
@fraserclark @cazinc It is fairly regular for an organization to have an internal DMP requirement for researchers (as in all employees of a lab or faculty in a department are required to create DMPs for their projects and submit them internally). In this case, the org admin would be creating a new DMP template and only want it to be visible to their organization.

**Comment by cazinc** [comment]
Hi @mariapraetzellis ok thanks for that further clarification. I just want to make sure that we're all on the same page as I think Visibility should maybe work differently depending on the type of Template. Does the below look right? 

**Template Type: Funder DMP Template**
Admin **cannot** set visibility, always Public. (A Funder is different from an Organisation; they would never want to limit scope, correct?)

**Template Type: Organisation DMP Template**
Admin can set visibility to Organisation only or Public as required. Default is Organisation only. (This is based on the use case in your last reply). 

**Template Type: Organisation _Overlay_**
Admin **cannot** set visibility. An Overlay is just for Researchers in a specific Org so it effectively has "Organisation Privacy" but really it's about who an Overlay is relevant to, not Visibility. 

On the Overlay, I thought there was perhaps a use case for an Org to want to make an Overlay Public if a Researcher from a different Org is involved in a Project, or is using a Field Station that's not part of their own Org. However, I think in the former case we handle this via Collaborators, and in the latter case an Org would create a whole different Template and make it Public. Here are some examples:

- Researchers at Org A have a Project. They set a Researcher from Org B as a Collaborator. Now, Researcher at Org B can see Org A Overlays. 
- Researchers from Org B are using a Field Station at Org A. Org A would create a separate Template and mark it Public so that it's available to the Org B Researchers. 

The first example above feels a bit complex. Can you confirm if some way of handling this use case is needed?

**Comment by mariapraetzellis** [comment]
@cazinc 

Funder DMP Template: There are use cases where funders **do** need to create templates that are only visible to their organization 

Organisation DMP Template: An org admin **can** set the visibility to Organization only or public. Default is Organization only. 

Template Type: Organisation Overlay: An org admin **cannot** set visibility because overlays are organization-specific. 

The first scenario above is how we'd like this handled: Researchers at Org A have a Project. They set a Researcher from Org B as a Collaborator. Now, Researcher at Org B can see Org A Overlays.

**Comment by fraserclark** [comment]
I have updated the DMP template editor wireframe to reflect the terminology  being used, and put a note with Maria's logic for clarity 

With the caveat that the actual text/description is TBC 

![Image](https://github.com/CDLUC3/dmsp_frontend_prototype/assets/113307/3a353733-cb35-4c12-bf1a-114add946200)
