### ISSUE TITLE
 Create Figma wireframes for guidance overlay (customization)

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmsp_frontend_prototype#52]
"Guidance overlay" describes a feature allowing an administrator to "overlay" a publicly available template with customized questions, sections, and question-specific guidance. The available customizations include:

- Provide example answers, and default answers
- Add customization to complex question widgets (institutional repo preferences, etc.) _(This may be better addressed in the Repository Selector _ [issue](https://github.com/orgs/CDLUC3/projects/14?pane=issue&itemId=58716866))
- Add their guidance group to a question (this is tagging)
- Provide guidance at the question level (this is guidance specific to a single question)
- Create additional questions 
- Add their own sections (with questions)

Additional requirements:
- New customized guidance (overlay) should continue to include all existing guidance from the original template. 
- When a question in the original template has changed (for example, a funder has changed the wording of a question): Display an alert for admin users when a template they have customized has changed and show the details of the change. Show the old/new questions side by side to allow the admin to reconcile.

Viewing this overlay when building a plan will only be available to users from the same organization/institution. One exception is that if a plan that has an overlay is shared with a researcher from another organization/institution, that user will view the guidance of the plan creator.

**Comment by cazinc** [comment]
Hello all, 

We've got a first draft of this ready for you. 

I've done a Fraser-style voice walk through, available at https://www.loom.com/share/26049b122164443aa1f634798b74c2d0?sid=0ffb1807-ad98-4289-a65b-c6a440840f48 (about 11 mins). 

The interactive prototype itself is at https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?page-id=325%3A351&node-id=413-1132&viewport=479%2C142%2C0.16&t=YZVs6Vo6G7lqMbkQ-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=413%3A1132.

Any questions please shout, otherwise look forward to seeing you all tomorrow and going through this then.

**Comment by bofstein** [comment]
I'm trying to review this today but I'm a bit unclear about the relationship between this guidance and the org guidance.  For example, this makes it seem like UCOP may have one policy for a template while this admin is overriding it for different guidance.  However, admins are specifically associated with the organization and are the ones that set up the org's guidance as far as I understand.  So I'm not sure how it comes in to play that a UCOP admin might override their own guidance - wouldn't they be the ones that set the original guidance and could just go change it?

![image](https://github.com/CDLUC3/dmsp_frontend_prototype/assets/23406931/c3df0a1b-c8f7-4581-9c5b-e548b20636eb)

**Comment by bofstein** [comment]
I'm also overall a bit unclear on the relationship between this flow and the Template builder flow which seems like the same idea - taking a basic start from a funder (e.g. a base NSF template) and adding org-specific guidance.  I may need to be given more context on this from Maria or others on the need here so I can give feedback.

**Comment by cazinc** [comment]
As discussed I've now created a dedicated card for feedback on this: #624
