### ISSUE TITLE
Clarify ways in which Orgs may wish to apply an Overlay

### ISSUE THREAD

**Issue by cazinc** [CDLUC3/dmsp_frontend_prototype#59]
We've come up with at least two ways that an Org may wish to apply an Overlay to a Funder Template:

1) Create a new Overlay for each Template.
2) Create a set of "Overlay Templates", for example one that applies to medical-related Funder Templates, one that applies to astrophysics-related Funder Templates, etc., and then apply the appropriate one to Funder Templates as needed. 

The user flow for each of these might look like this:
1) New Funder Template created → Org creates an Overlay for that Template → Done
2) New Funder Template created → Org picks appropriate "Overlay Template" and applies that → Org customises the Overlay as needed → Done

Option 2 might offer some time-savings to Orgs, but it could also get really messy: you can imagine a situation where the list of Overlay Templates gets big and unruly, with the differences between them not quite clear. This is also obviously the more complex one to build (front and backend), for example it would require a whole new set of Overlay Templates, with all the related functionality to create/edit/duplicate/update. I'd expect this to have a related effect on scope, timings and budget too. I worry this also opens us up to users asking if they could have "layers of Overlays", like multiple Overlays that they design to apply to different bits of a Template - or other things similarly complex (which sounds great but might be better as a later phase, once we know how they are using the Overlays). 

With Option 1, we are planning to integrate the same sort of functionality from Plan Builder that lets a user pull from a library. There it's a library of previous answers to Questions, here it would be "pull from a library of Guidance text you've entered in a similar Overlay". We think this offers a similar time savings to the user without the added complexity. 

Let us know your thoughts or questions on the above, or if we've missed any other ways that an Org might want to work with these Overlays.

**Comment by cazinc** [comment]
@briri this is the question we briefly discussed in Tuesday's (June 11) meeting, just putting here as promised to get input from all.

**Comment by mariapraetzellis** [comment]
If I understand this correctly, workflow option **one** will give us what we need. The ability to "pull from a question library" will allow users to add institutional guidance to an existing public template. The principal use case of a customized template is for DMP Tool administrators to add questions or guidance to an existing template specific to their institution, and the question/guidance library feature will allow them to do this. 

@cazinc @fraserclark

**Comment by cazinc** [comment]
Great, thanks @mariapraetzellis.

**Comment by mariapraetzellis** [comment]
@cazinc @fraserclark : any additional questions on this or can we close the issue? Thanks

**Comment by cazinc** [comment]
No further questions @mariapraetzellis, good to close this.
