### ISSUE TITLE
Update authentication-related code in the frontend once the backend auth updates have been checked in

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_frontend_prototype#63]
There will be lots of auth code changes in the backend once this code is merged: https://github.com/CDLUC3/dmsp_backend_prototype/issues/2

So the frontend will need to make some updates to its auth code to make it work with the changes

**Comment by jupiter007** [comment]
Blocked by https://github.com/CDLUC3/dmsp_backend_prototype/issues/2

**Comment by briri** [comment]
finished up the changes to the backend. We might need to make some adjustments though as we get the frontend hooked up to use the new auth.

The `/signup` endpoint is now creating a DB record and should return a JWT when successful. 
The `/signin` endpoint should return the JWT if successful

Some things to test for sign up:
- invalid passwords (should return message)
- invalid email address (should return message)
- pass `givenName` and `surName`
- JWT is returned
- JWT has correct user info (and does not include the user's password)
- Properly handling failures/errors
- 
Some things to test for sign in:
- JWT is returned
- JWT has correct user info (and does not include the user's password)
- Properly handling failures/errors
