### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmsp_frontend_prototype#65]
This ticket is blocked by: https://github.com/CDLUC3/dmsp_backend_prototype/issues/43

Once the above is complete, then add a logout button that calls that endpoint, and subsequently deletes the JWT token cookie.

**Comment by bofstein** [comment]
Start with removing cookie rather than waiting on #43

**Comment by jupiter007** [comment]
Switched back to "In Progress" since I want to add some handling of context for authentication.
