### ISSUE TITLE
Build components into style guide based on template builder

### ISSUE THREAD

**Issue by fraserclark** [CDLUC3/dmsp_frontend_prototype#75]
Expanding on Andre work on the style guide, start building and applying the initial styling from the wireframe to the main components that have been agreed

- Text Input
- Text Area
- Radio buttons
- Select box
- Checkbox
- Primary Button
- Secondary Button
- Back button
- "Add Section" skelton
- Cards
- Sectional Cards
- Tabs

**Comment by fraserclark** [comment]
@jupiter007 I will update this card on Monday. I was off sick at the beginning of the week, so catching up a bit.

Just aiming to get the following ticked off, most have already been as its been styling the react-aria styling but just want to clean my code up a little

- Text Input
- Text Area
- Radio buttons
- Select box
- Checkbox
- Primary Button
- Secondary Button
- Back button
- "Add Section" skeleton

I also have Question/Sectional "card" style in progress but I will split this into a new card as you suggested.

**Other**
- Cards
- Tabs

I suspect we might need to split these off a little, as I think tabs might come with some chat required and yeah I know youve already put cards elsewhere and we know cards might become "list" based on wireframe feedback so we dont want to take this too far.

**Comment by jupiter007** [comment]
Thanks for the update @fraserclark. Good point about cards becoming Lists.

**Comment by fraserclark** [comment]
@andrewebdev @jupiter007 @briri 

**Video on update**
https://www.loom.com/share/ee503e9419af41f097ed41db97c71cf8

**Syntax Highlighting in style guide**

What is your opinion of us getting some syntax highlighting library installed to make the style guide a bit easier to work with so we can copy and paste or do you guys see moving this style guide into [Storybook](https://storybook.js.org/) or something like that?

**Select**
React-aria has a custom select box component. When I tried it on mobile it 'breaks' the standard built in "select" functionality on iOS and Android - which isn't great

https://react-spectrum.adobe.com/react-aria/Select.html

They also mention issues with accessibility testing, although they claim it is accessible
https://react-spectrum.adobe.com/react-aria/Select.html#accessibility

How should we proceed - should we do style the react-aria one and also create an alternative more traditional html select? I don't like the modification of native elements generally.

I would say in the wireframes at the moment, we have, where possible, tried to avoid using <select> whenever possible to be aligned with [UK Government](https://design-system.service.gov.uk/components/select/), USWDS and many similar user testing's recommendations that a <select> should only be used as a last resort

**Comment by jupiter007** [comment]
@fraserclark , based on React Aria's documentaiton, their custom select does support the ARIA listbox pattern and keyboard navigation, so I'm thinking it will be ok to use it even as long as it is functioning as expected on different devices.

I can do a quick test using my Mac's VoiceOver. Also, we could seek the assistance of the accessibility team here to confirm that this component is compliant.

In regards to Syntax highlighting, I like the idea of using Storybook for documenting our components.

**Comment by fraserclark** [comment]
Pull request here

https://github.com/CDLUC3/dmsp_frontend_prototype/pull/120

**Comment by jupiter007** [comment]
> @jupiter007 I will update this card on Monday. I was off sick at the beginning of the week, so catching up a bit.
> 
> Just aiming to get the following ticked off, most have already been as its been styling the react-aria styling but just want to clean my code up a little
> 
> * Text Input
> * Text Area
> * Radio buttons
> * Select box
> * Checkbox
> * Primary Button
> * Secondary Button
> * Back button
> * "Add Section" skeleton
> 
> I also have Question/Sectional "card" style in progress but I will split this into a new card as you suggested.
> 
> **Other**
> 
> * Cards
> * Tabs
> 
> I suspect we might need to split these off a little, as I think tabs might come with some chat required and yeah I know youve already put cards elsewhere and we know cards might become "list" based on wireframe feedback so we dont want to take this too far.

@fraserclark sorry to hear you were sick. Hope you are feeling better now.

Don't worry about the Cards and Tabs. There's a separate ticket for Cards [here](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/83), and you can add the Tabs work there. This PR is already huge anyways, so lets keep them separate.
