### ISSUE TITLE
Wireframe for Login/Logout flow

### ISSUE THREAD

**Issue by fraserclark** [CDLUC3/dmsp_frontend_prototype#76]
- Login (can be the same)
- User sign-up (add email verification)
- Logout

Details To come

**Comment by fraserclark** [comment]
Here are the login/register flow for review 

SSO Login
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=736-1384&t=PKk0pf2RKfCQqKPt-9&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1384&show-proto-sidebar=1

Password Login
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=736-1633&t=PKk0pf2RKfCQqKPt-9&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1633&show-proto-sidebar=1

Register
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=736-1772&t=PKk0pf2RKfCQqKPt-9&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=736%3A1772&show-proto-sidebar=1

Profile
https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Explain?node-id=771-1054&t=PKk0pf2RKfCQqKPt-9&scaling=min-zoom&content-scaling=fixed&page-id=736%3A1383&starting-point-node-id=771%3A1054&show-proto-sidebar=1

**Comment by briri** [comment]
@bofstein and @mariapraetzellis how do you feel about these wireframes for user sign in/up and their profile page?

**Comment by bofstein** [comment]
The password login is missing a Forgot Password option I think we need to add before we can call this one complete.  There's also a couple comments on the email list in the profile page to address, even if addressing means we decide not to make changes.  Once those are done I think we can close the ticket.
