### ISSUE TITLE
Decide and integrate on a Icon set or Library (FontAwesome or Google Material)

### ISSUE THREAD

**Issue by bofstein** [CDLUC3/dmsp_frontend_prototype#80]
We need to pick an icon library to use.

We could use FontAwesome since it's popular. They do have some limitations when
using the non-paid icons, however.

Google’s material icons is another option. Not as expansive as the **paid**
FontAwesome set. It does have a good range of symbols and icons available for
free. Another benefit of this set is that it is consistent with other
Google products, and Android phones.

[1] - https://fontawesome.com/
[2] - https://fonts.google.com/icons

**Comment by bofstein** [comment]
I'll let you all decide for sure but we probably want to lean towards the most expansive free one if it gets what we want, limit payment where we can

**Comment by cazinc** [comment]
All agreed to go with Material icons @andrewebdev.

**Comment by andrewebdev** [comment]
I'll add this into our base then

**Comment by jupiter007** [comment]
Just a question whether we should be using svg, like the @mui/icons-material package or not.

**Comment by andrewebdev** [comment]
I thought you saw my answer on the other PR related to the same question. I'll post it here again:

> I have a couple of opinions on this (and I'm happy to have them challenged :wink: )
> 
> 1. I chose the font version instead of the SVG version because it's a standard that many other platforms started adopting
> 2. We can download the font and load it locally, just like the other ones you pointed out.
> 3. I normally start out loading fonts direct from google and make use of their CDN. Performance is rarely an issue, but when it becomes a problem, that's when I download the font locally.
> 4. I would rather use the font library of the icons, over another third party that wraps them. It introduces yet another dependency (and whatever other dependencies they import), and makes security more fickle down the line.
> 
> I'm happy to be challenged on these points, and even though I feel strongly about it, I'll change it if you want me to :)

**Comment by jupiter007** [comment]
Hi @andrewebdev. I did see your comment in the other Remirror ticket, but wanted to add the question about whether to use svgs or load the font family here, so that we remember to make a decision before closing this ticket.

I'll try and do some more research on it and get back to you.
